# Support DONGOL Development
# Dukung Pengembangan DONGOL

github: [dongol-org]
patreon: dongol
ko_fi: dongol

custom:
  - "https://saweria.co/dongol"  # Indonesian payment
  - "https://trakteer.id/dongol"  # Indonesian payment
